growup-elasticsearch:
  container_name: growup-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/Growup/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
growup-postgresql:
  container_name: growup-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/Growup/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=Growup
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
